switches:
  configVersion: 0
config:
  messages:
    prefix: "&4&lCNHC>> "
    access-denied: "&cAccess denied."
    reload-warn: "&c&lWARNING: &cReloading is not advised as it may have some unintended consequences. It is recommended you always restart the server!"