# DO NOT CHANGE THIS SECTION
switches:
  configVersion: 0

# Plugin configuration
config:
  messages:
    prefix: "&4&lCNHC>> "
    access-denied: "&cAccess denied."
    reload-warn: "&c&lWARNING: &cReloading is not advised as it may have some unintended consequences. It is recommended you always restart the server!"
    death: "&cYou have died! You may spectate the server in Spectator Mode until the next hardcore reset."\
    revive-success: "&aPlayer revived successfully!"
    revive-fail: "&cFailed to revive player!"
    not-online: "&cPlayer not online"
  death-options:
    # reserved for future use
    track-deaths: true
    # Group to assign to dead players
    dead-group: hc-dead
    # Server context for LP
    server-context: hardcore
  features:
    # place dead players in spectator mode on login
    dead-gmsp-login: true
    # place alive players in survival mode on login
    alive-gms-login: true
    # allow revival of any form
    allow-revive: true