name: CN-Hardcore
main: me.kevsal.minecraft.cnhardcore.CNHC
version: 1.0-SNAPSHOT
author: Kevinjss1
api-version: 1.14
commands:
  hc-version:
    description: Get the plugin version
    usage: /<command>
    permission: cnhc.version
    aliases: [cnhc-version]
  hc-reload:
    description: Reload the plugin
    usage: /<command>
    permission: cnhc.reload
    aliases: [cnhc-reload]
permissions:
  cnhc.version:
    default: op
  cnhc.reload:
    default: op