name: CN-Hardcore
main: me.kevsal.minecraft.cnhardcore.CNHC
version: 1.0-SNAPSHOT
author: Kevinjss1
api-version: 1.14
depend: [LuckPerms]
commands:
  hc-version:
    description: Get the plugin version
    usage: /<command>
    aliases: [cnhc-version]
  hc-reload:
    description: Reload the plugin
    usage: /<command>
    aliases: [cnhc-reload]
  hc-revive:
    description: Revive a dead player (MUST BE ONLINE)
    usage: /<command> <username>
    aliases: [cnhc-revive, revive]
permissions:
  cnhc.version:
    default: op
  cnhc.reload:
    default: op
  cnhc.revive:
    default: op